CREATE DATABASE APP_DELICARE;
USE APP_DELICARE;


CREATE TABLE PROVINCE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NULL,
	CODE VARCHAR(255) NULL,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE DISTRICT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NULL,
	CODE VARCHAR(255) NULL,
	PROVINCE_ID INT,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE WARD (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NULL,
	CODE VARCHAR(255) NULL,
	DISTRICT_ID INT,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE DEPARTMENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NULL,
    CODE VARCHAR(150) NULL,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE GROUPS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NULL,
    CODE VARCHAR(150) NULL,
	DEPARTMENT_ID INT,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE TITLE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NULL,
    CODE VARCHAR(150) NULL,
	TYPE TINYINT(1) DEFAULT 0,
	ALIAS_NAME VARCHAR(150) NULL,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE USERS (
	ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(255) NULL,
	USER_NAME VARCHAR(255) NULL,
	USER_TYPE TINYINT(1) DEFAULT 0,
	PHONE_NUMBER VARCHAR(50) NULL,
	PASSWORD VARCHAR(255) NULL,
	FIRST_NAME VARCHAR(255) NULL,
	LAST_NAME VARCHAR(255) NULL,
	GENDER VARCHAR(50) NULL,
	EMAIL VARCHAR(255) NULL,
	BIRTH_DAY DATE NULL,
	COMPANY_ID INT,
	LEVEL_ORG_CHART TINYINT(1) DEFAULT 0,
	IS_MANAGER TINYINT(1) DEFAULT 0,
	GROUP_ID INT,
	DEPARTMENT_ID INT,
	TITLE_USER_ID INT,
	ROLE_ID INT,
    PROVINCE_ID VARCHAR(24) NULL,
	DISTRICT_ID VARCHAR(24) NULL,
	WARD_ID VARCHAR(24) NULL,
	STREET VARCHAR(255) NULL,
	MAP_ID VARCHAR(255) NULL,
	LONGITUDE VARCHAR(255) NULL,
	LATITUDE VARCHAR(255) NULL,
	STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);


CREATE TABLE USER_HISTORY (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_ID INT,
	NAME VARCHAR(255) NULL,
	USER_NAME VARCHAR(255) NULL,
	USER_TYPE TINYINT(1) DEFAULT 0,
	PHONE_NUMBER VARCHAR(50) NULL,
	PASSWORD VARCHAR(255) NULL,
	FIRST_NAME VARCHAR(255) NULL,
	LAST_NAME VARCHAR(255) NULL,
	GENDER VARCHAR(50) NULL,
	EMAIL VARCHAR(255) NULL,
	BIRTH_DAY DATE NULL,
	COMPANY_ID INT,
	LEVEL_ORG_CHART TINYINT(1) DEFAULT 0,
	IS_MANAGER TINYINT(1) DEFAULT 0,
	GROUP_ID INT,
	DEPARTMENT_ID INT,
	TITLE_USER_ID INT,
	ROLE_ID INT,
    PROVINCE_ID VARCHAR(24) NULL,
	DISTRICT_ID VARCHAR(24) NULL,
	WARD_ID VARCHAR(24) NULL,
	STREET VARCHAR(255) NULL,
	MAP_ID VARCHAR(255) NULL,
	LONGITUDE VARCHAR(255) NULL,
	LATITUDE VARCHAR(255) NULL,
	STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE TOKEN (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(150) NOT NULL,
	TOKEN VARCHAR(255) UNIQUE NOT NULL,
    TOKEN_TYPE VARCHAR(50) NOT NULL,
	EXPIRATION_DATE DATETIME,
	REVOKED TINYINT(1) NOT NULL,
	EXPIRED TINYINT(1) NOT NULL,
	USER_ID VARCHAR(24),
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE ROLE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(150) NOT NULL,
	CODE VARCHAR(50) NOT NULL,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE ROLE_USER (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(150) NOT NULL,
	ROLE_ID INT,
	USER_ID INT,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE FUNCTIONS (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(150) NOT NULL,
	CODE VARCHAR(50) NOT NULL,
	IS_DISPLAY TINYINT(1) DEFAULT 0,
	ICON_PATH VARCHAR(255),
	PARENT_ID VARCHAR(24),
	ORDER_DISPLAY INT DEFAULT 0,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE ACTIONS (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(150) NOT NULL,
	CODE VARCHAR(50) NOT NULL,
	IS_DISPLAY TINYINT(1) DEFAULT 0,
	ORDER_DISPLAY INT DEFAULT 0,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE FUNCTION_ACTION (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(150) NOT NULL,
	FUNCTION_ID INT,
	ACTION_ID INT,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE ROLE_FUNCTION (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(150) NOT NULL,
	ROLE_ID INT,
	FUNCTION_ID INT,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE USER_FUNCTION (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(150) NOT NULL,
	USER_ID INT,
	FUNCTION_ID INT,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE STAGE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NULL,
	CODE VARCHAR(255) NULL,
	TYPE VARCHAR(255) NULL,
	SORT INT DEFAULT 0,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE USER_CONTACT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NULL,
	USER_ID INT,
	PHONE_NUMBER VARCHAR(50) NULL,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE USER_ADDRESS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NULL,
	USER_ID INT,
	PROVINCE_ID VARCHAR(24) NULL,
	DISTRICT_ID VARCHAR(24) NULL,
	WARD_ID VARCHAR(24) NULL,
	STREET VARCHAR(255) NULL,
	MAP_ID VARCHAR(255) NULL,
	LONGITUDE VARCHAR(255) NULL,
	LATITUDE VARCHAR(255) NULL,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);



CREATE TABLE UNITS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NULL,
	CODE VARCHAR(255) NULL,
	TYPE VARCHAR(255) NULL,
	SORT INT DEFAULT 0,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE INGREDIENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NULL,
	CODE VARCHAR(255) NULL,
	UNIT_ID INT,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE RECIPES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NULL,
	CODE VARCHAR(255) NULL,
	TYPE VARCHAR(255) NULL,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE RECIPE_INGREDIENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    RECIPE_ID INT,
	INCREMENT_ID INT,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE PRODUCTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NULL,
	CODE VARCHAR(255) NULL,
	TYPE VARCHAR(255) NULL,
	ICON_PATH VARCHAR(255) NULL,
	SORT INT DEFAULT 0,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE PRODUCT_IMG (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_ID INT,
	IMG_PATH VARCHAR(255) NULL,
	SORT INT DEFAULT 0,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);


CREATE TABLE MENU (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NULL,
	CODE VARCHAR(255) NULL,
	TYPE VARCHAR(255) NULL,
	ICON_PATH VARCHAR(255) NULL,
	SORT INT DEFAULT 0,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);


CREATE TABLE MENU_PRODUCT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MENU_ID INT,
	PRODUCT_ID INT,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE MENU_DAY (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MENU_ID INT,
	MENU_DATE DATE,
	MENU_WEEK INT,
	MENU_MONTH INT,
	MENU_YEAR INT,
	MENU_MONTH_KEY INT,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE ORDERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
	USER_ID INT,
	PHONE_NUMBER VARCHAR(500) NULL,
	ORDER_DATE DATETIME,
	STAGE_ID INT,
	AMOUNT_TOTAL INT,
	PAYMENT_ID INT,
	PAYMENT_STATUS_ID INT,
	SHIPPING_ID INT,
	SHIPPING_STATUS_ID INT,
	USER_ADDRESS_ID INT,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE ORDER_DETAIL (
    ID INT PRIMARY KEY AUTO_INCREMENT,
	ORDER_ID INT,
	MENU_ID INT,
	QUANTITY INT,
	PRICE INT,
	AMOUNT_TOTAL INT,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE PAYMENTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NULL,
	CODE VARCHAR(255) NULL,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE SHIPPING (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NULL,
	CODE VARCHAR(255) NULL,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);

CREATE TABLE CATEGORY (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NULL,
	CODE VARCHAR(255) NULL,
	TYPE VARCHAR(255) NULL,
	SORT INT DEFAULT 0,
    STATUS TINYINT(1) DEFAULT 1,
	DELETED TINYINT(1) DEFAULT 0,
	DESCRIPTION VARCHAR(500) NULL,
    CREATED_AT DATETIME,
    MODIFIED_AT DATETIME,
    CREATED_BY_ID INT,
    MODIFIED_BY_ID INT
);




